#!/usr/bin/env bash


BB_FINDER_SEARCH_EXCLUDES=(\
	-not -path "*/debian/*" \
	-not -path "*/build/*" \
	-not -path "*.svn*" \
	-not -path "*/node_modules/*" \
	-not -path "*CVS*" \
	-not -path "*.git*" \
	-not -name "*.py?" \
	-not -name ".*.sw?"\
)

BB_FINDER_GREP_OPTIONS=(\
	--color=auto -I\
)

BB_FINDER_XAGRS_OPTIONS=()

BB_FINDER_FANCY=$(which rg)
BB_FINDER_FANCY=${BB_FINDER_FANCY:-$(which ack)}
BB_FINDER_FANCY=${BB_FINDER_FANCY:-$(which ag)}

if [ -z "$BB_FINDER_FANCY" ] ; then
    function gg() {
        local dir="."
        if [ -e "$1" ] && [ -n "$2" ] ; then
            dir=$1
            shift
        fi

        find $dir -type f "${BB_FINDER_SEARCH_EXCLUDES[@]}" -print0 \
            | xargs -0 "${BB_FINDER_XARGS_OPTIONS[@]}" grep "${BB_FINDER_GREP_OPTIONS[@]}" "$@"
    }
else
    alias gg=$BB_FINDER_FANCY
fi

function ff() {
	local dir="."
	if [ -e "$1" ] && [ -n "$2" ] ; then
		dir=$1
		shift
	fi
	local name=${1:-"*"}
	shift

	find $dir "${BB_FINDER_SEARCH_EXCLUDES[@]}" -iname '*'$name'*' "$@" 
}

